name: build

on: push

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v4
      - name: Setup up JDK 21 for x64
        uses: actions/setup-java@4
        with:
          java-version: '21'
          distribution: 'termurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew build
        
